[project]
name = "pandamesh"
version = "0.1.5"
description = "From geodataframe to mesh"
authors = ["Huite Bootsma <huitebootsma@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]

[tasks]
install = "python -m pip install --no-deps --editable ."
install-pre-commit = "pre-commit install"
pre-commit = "pre-commit run --all-files"
test = { depends_on = ["install"], cmd = "pytest --cov=pandamesh --cov-report xml --cov-report term"}
docs = { depends_on = ["install"], cmd = "sphinx-build docs docs/_build"}
all = { depends_on = ["pre-commit", "test", "docs"]}
pypi-publish = { cmd = "rm --recursive --force dist && python -m build && twine check dist/* && twine upload dist/*" }

[dependencies]
build = "*"
geopandas = "*"
python-gmsh = "*"
matplotlib = "*"
pooch = "*"
pip = "*"
pre-commit = "*"
pydata-sphinx-theme = "*"
py-triangle = "*"
pytest = "*"
pytest-cov = "*"
shapely = ">=2.0"
sphinx = "*"
sphinx-gallery = "*"
hatchling = "*"
jupyter = "*"
twine = "*"
