name: docs

on:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      # Copied from: https://github.com/nschloe/pygmsh/blob/main/.github/workflows/ci.yml
      # install gmsh from system -- not sure why this is necessary
      - name: Install gmsh
        run: |
          sudo apt-get install -y python3-gmsh

      - name: Install dependencies
        run: |
          pip install -e ".[docs]"
      - name: Run sphinx
        run: make html
        working-directory: docs

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
